.TH "GGClient" 3 "Sat Jun 29 2019" "Version 1.0" "SIGNALR GG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GGClient
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProgram\fP"
.br
.ti -1c
.RI "class \fBWinFormsClient\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SIGNALR GG from the source code\&.
