.TH "GGClient.WinFormsClient" 3 "Sat Jun 29 2019" "Version 1.0" "SIGNALR GG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GGClient.WinFormsClient
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file WinFormsClient\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void GGClient\&.WinFormsClient\&.Dispose (bool disposing)\fC [inline]\fP, \fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.PP
Definition at line 14 of file WinFormsClient\&.Designer\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SIGNALR GG from the source code\&.
